clear all;
num=[1 -2];
den=[1 3 3 1 0];
[z p k]=tf2zp(num,den);
zplane(z,p);
title('1) F_1(s)零极点图');
figure;
freqs(num,den);
title('1) F_1(s)=幅频响应图') ;
figure; 
num=[1 4 3]; 
den=[1 7 10 0]; 
[z p k]=tf2zp(num,den);
zplane(z,p); 
title('1) F_2(s)零极点图');
figure; 
freqs(num,den); 
title('1) F_2(s)幅频响应图');
figure;
x1=-4:0.05:4; 
y1=-4:0.05:4;
[x y]=meshgrid(x1,y1);
s=x+i*y; 
Fs=abs((s-2)./(s.*(s+1).*(s+1).*(s+1)));
mesh(x,y,Fs); 
surf(x,y,Fs);
title('F_1(s)三维曲面图');
zlim([-1 100]); 
colormap(hsv);
figure; 
Gs=abs((s+1).*(s+3)./(s.*(s+2).*(s+5))); 
mesh(x,y,Gs);
surf(x,y,Gs);
title('F_2(s)三维曲面图');
zlim([-1 10]);
colormap(hsv); 
figure; 
syms s; 
Fs1=(s-2)/(s*(s+1)^3);
ft1=ilaplace(Fs1);
subplot(211); 
ezplot(ft1); 
Fs2=(s+1)*(s+3)/(s*(s+2)*(s+5));
f2=ilaplace(Fs2);title('原函数f_1(t)');
grid on; subplot(212);
ezplot(f2);title('原函数f_2(t)');grid on;
